### ISSUE TITLE
GUI could benefit from minor improvements

### ISSUE THREAD

**Issue by kstenio** [b-pardi/BraTaDio#5]
The GUI application is written in Tk, which is fine (although I would recommend checking out a more modern framework, like [PySide6](https://pypi.org/project/PySide6/)), but the size of the window is constant. If the user resolution is set to fullhd (1920x1080, a common standard nowadays), when maximizing the application, there is no issues. The same can not be said for smaller screens (e.g. 14" laptops). My recommendation is implementing properly responsivity. Non mandatory, but recommended. For what I've searched, [this](https://stackoverflow.com/questions/46522051/python-tkinter-responsive-grid) could be a start.

Another problem I've seen is regarding the input boxes. You used the same text input for all fields, but some are strictly numbers (baseline, visualize overtone, maybe others). For those, try using a [spinbox](https://www.tutorialspoint.com/python/tk_spinbox.htm).

Also, it is very unclear to me when the plots are computed. It took a while to understand that the plots are performed when clicking "submit". To me, "save graphics" or "perform plots" would be better. You could also show a messagebox, maybe with a link for the folder (html), when the process is finished. If you use `pathlib` library, it would be something like `folder_str = f'<a href={folder_path.as_uri()}>{folder_path.name}</a>'`

Finally, I noticed that it is not possible to deselect "interactive plot" radio button in raw and shifted data overtone selection.

**Comment by b-pardi** [comment]
Thank you for these improvements. I will focus on the more important required things for now, but these are things I will definitely implement shortly after.

**Comment by kstenio** [comment]
> Thank you for these improvements. I will focus on the more important required things for now, but these are things I will definitely implement shortly after.

No worries. You can address the issues by priority.

**Comment by b-pardi** [comment]
All UI adjustments should have been made. Please open another issue if something was missed.

**Comment by kstenio** [comment]
> All UI adjustments should have been made. Please open another issue if something was missed.

I've confirmed (at least for my configuration) that the program only quits if I click the "Exit" button inside application, but not if I click the "X" in the bar.

The program was opened from a terminal (`python main.py`) and I had to use Ctrl+Z to escape.

**Comment by b-pardi** [comment]
looking into this now.

**Comment by b-pardi** [comment]
should be remedied

**Comment by kstenio** [comment]
> should be remedied

I confirm that the changes addressed the issue. :+1:
