### ISSUE TITLE
Plots show warning for font on linux system when font not found

### ISSUE THREAD

**Issue by b-pardi** [b-pardi/BraTaDio#8]

**Comment by b-pardi** [comment]
@kstenio if your system does not have the default font (Arial) then you can change it to a font or font family of your choosing in the plot customization window shown below:

![image](https://github.com/b-pardi/BraTaDio/assets/72064522/ca4e5124-5286-4c0a-92c1-21d3fb447433)

Note, if you want to do sans serif, do not use the dash, i.e. type 'sans serif' not 'sans-serif' (without the quotes of course)
The next commit will have this noted in the README in the plot customization section (section 1.1)

**Comment by kstenio** [comment]
I confirm this is working. Used "Liberation Sans" in the option above and the warning regarding "Arial" font disappeared. :+1:
